Repository fga-gpp-mds/2018.1-TropicalHazards-BI, pull requests merged in 2018-04, with the labels that each got.

#132 Issue 124 configuração do pyup
  .pyup.yml
  README.md
Labels: EPS, Planned, dev-ops, enhancement, pending review

#138 Issue 127 risk burndown
  docs/wiki/riscos.md
Labels: EPS, PO, Scrum Master, documentation, gh-pages, pending review

#144 Issue 84 package diagram of architecture document
  docs/doc_arquitetura.md
  docs/images/Diagrams/diagrama_de_pacotes.png
Labels: MDS, documentation, enhancement

#135 Issue 121 atualizar configuração de coleta de métricas
  .codeclimate.yml
  .coveralls.yml
  .travis.yml
  README.md
  requirements.txt
Labels: EPS, Planned, dev-ops, enhancement, pending review

#146 Sprint 03 and 04 documentation
  docs/wiki/R1/sprint_02/sprint_02_review.md
  docs/wiki/R1/sprint_03/sprint_03_planning.md
  docs/wiki/R1/sprint_03/sprint_03_review.md
  docs/wiki/R1/sprint_04/sprint_04_planning.md
Labels: Scrum Master, documentation, enhancement, pending review

#142 Issue 126 matriz de dependências
  docs/wiki/matriz-de-dependencia.md
Labels: EPS, Planned, documentation, enhancement, pending review

#153 [MERGE] Sprint 04
  .codeclimate.yml
  .coveralls.yml
  .gitignore
  .pyup.yml
  .travis.yml
  README.md
  TropicalHazards_BI/settings.py
  docs/Dockerfile
  docs/Gemfile
  docs/_config.yml
  docs/_layouts/default.html
  docs/doc_arquitetura.md
  docs/docsmap.html
  docs/how-to-run-locally.md
  docs/images/Diagrams/diagrama_de_pacotes.png
  docs/metodologia.md
  docs/wiki/R1/sprint_02/sprint_02_review.md
  docs/wiki/R1/sprint_03/sprint_03_planning.md
  docs/wiki/R1/sprint_03/sprint_03_review.md
  docs/wiki/R1/sprint_04/sprint_04_planning.md
  docs/wiki/doc_visao.md
  docs/wiki/matriz-de-dependencia.md
  docs/wiki/riscos.md
  requirements.txt
Labels: enhancement

#160 Issue 141 arquitetura dos servicos
  docs/wiki/doc_arquitetura.md
Labels: EPS, Planned, documentation, enhancement, hard

#171 Issue 141 arquitetura dos servicos
  docs/wiki/doc_arquitetura.md
Labels: Architect, EPS, Planned, documentation, enhancement, pending review

#184 Config pyup to only check security updates weekly
  .pyup.yml
Labels: bug, dependencies, enhancement, repo workflow

#148 Issue 67 issue workflow
  docs/docsmap.html
  docs/issue_workflow.md
Labels: EPS, Important, documentation, easy, repo workflow

#191 Issue 140 roadmap papeis
  docs/wiki/ROADMAP_PAPEIS/Imagens/PAPEL_ARQUITETO.png
  docs/wiki/ROADMAP_PAPEIS/Imagens/PAPEL_PO_R1.png
  docs/wiki/ROADMAP_PAPEIS/Imagens/PAPEL_PO_R2.png
  docs/wiki/ROADMAP_PAPEIS/Imagens/papel_designer.png
  docs/wiki/ROADMAP_PAPEIS/Imagens/papel_devops.png
  docs/wiki/ROADMAP_PAPEIS/Imagens/scrum_master.png
  docs/wiki/ROADMAP_PAPEIS/index.md
Labels: Architect, EPS, Important, PO, Scrum Master, Too important!, design, dev-ops, documentation, work in progress

#173 Sprint 04 and 05 documentation
  docs/wiki/R1/sprint_02/sprint_02_review.md
  docs/wiki/R1/sprint_03/sprint_03_review.md
  docs/wiki/R1/sprint_04/sprint_04_review.md
  docs/wiki/R1/sprint_05/sprint_05_planning.md
Labels: EPS, Scrum Master, documentation, enhancement

#201 issue 187 Atualizar README
  README.md
Labels: Planned, docker, documentation, easy, enhancement, hotfix

#152 Issue 134 model canvas
  docs/_layouts/default.html
  docs/index.html
  docs/project_artefacts/canvas/canvas.png
  docs/project_artefacts/canvas/index.md
  docs/project_artefacts/prototipos/Alta Fidelidade/css/home.css
  docs/project_artefacts/prototipos/Alta Fidelidade/css/land.css
  docs/project_artefacts/prototipos/Alta Fidelidade/css/modals_and_forms.css
  docs/project_artefacts/prototipos/Alta Fidelidade/homepage.html
  docs/project_artefacts/prototipos/Alta Fidelidade/img/laptop-on-desktop.jpg
  docs/project_artefacts/prototipos/Alta Fidelidade/img/v3_rect.png
  docs/project_artefacts/prototipos/Alta Fidelidade/img/v3_round.png
  docs/project_artefacts/prototipos/Alta Fidelidade/js/home.js
  docs/project_artefacts/prototipos/Alta Fidelidade/js/main.js
  docs/project_artefacts/prototipos/Alta Fidelidade/js/modals_and_forms.js
  docs/project_artefacts/prototipos/Alta Fidelidade/landing-page.html
  docs/project_artefacts/prototipos/Alta Fidelidade/modals_and_forms.html
  docs/project_artefacts/prototipos/Alta Fidelidade/observatory.html
  docs/project_artefacts/prototipos/Alta Fidelidade/project-especific.html
  docs/project_artefacts/prototipos/Alta Fidelidade/search-projects.html
  docs/project_artefacts/prototipos/Baixa Fidelidade/prototipo_baixa.md
Labels: Important, PO, Product, documentation, pending review

#158 Issue 9 creating supplementary documentation document
  README.md
  docs/_layouts/default.html
  docs/development_docs/doc_especificacao_suplementar.md
  docs/index.html
  docs/project_artefacts/canvas/canvas.png
  docs/project_artefacts/canvas/index.md
  docs/project_artefacts/prototipos/Alta Fidelidade/css/home.css
  docs/project_artefacts/prototipos/Alta Fidelidade/css/land.css
  docs/project_artefacts/prototipos/Alta Fidelidade/css/modals_and_forms.css
  docs/project_artefacts/prototipos/Alta Fidelidade/homepage.html
  docs/project_artefacts/prototipos/Alta Fidelidade/img/laptop-on-desktop.jpg
  docs/project_artefacts/prototipos/Alta Fidelidade/img/v3_rect.png
  docs/project_artefacts/prototipos/Alta Fidelidade/img/v3_round.png
  docs/project_artefacts/prototipos/Alta Fidelidade/js/home.js
  docs/project_artefacts/prototipos/Alta Fidelidade/js/main.js
  docs/project_artefacts/prototipos/Alta Fidelidade/js/modals_and_forms.js
  docs/project_artefacts/prototipos/Alta Fidelidade/landing-page.html
  docs/project_artefacts/prototipos/Alta Fidelidade/modals_and_forms.html
  docs/project_artefacts/prototipos/Alta Fidelidade/observatory.html
  docs/project_artefacts/prototipos/Alta Fidelidade/project-especific.html
  docs/project_artefacts/prototipos/Alta Fidelidade/search-projects.html
  docs/project_artefacts/prototipos/Baixa Fidelidade/prototipo_baixa.md
Labels: EPS, MDS, pending review

#231 Product promo ghpages
  docs/css/banner-home-01.png
  docs/css/pesquization.png
  docs/css/shared.css
  docs/index.html
Labels: Not planned, PO, design, enhancement, feedback, gh-pages

#238 Issue 188 Refatorar Roadmap
  docs/metodology/roadmaps/Roadmapv2.png
Labels: EPS, Planned, documentation, enhancement

#241 Sprint 05 and 06 documentation
  docs/metodology/sprints/sprint_05/sprint_05_review.md
  docs/metodology/sprints/sprint_06/sprint_06_planning.md
Labels: Important, Scrum Master, documentation, enhancement

#246 Configure mongoDB service
  TropicalHazards_BI/settings.py
  docker-compose.yml
  requirements.txt
Labels: Architect, EPS, dev-ops, enhancement, pending review

#251 [ADD] paths and links for SWOT in gh-pages
  docs/_layouts/default.html
  docs/docsmap.html
  docs/index.html
  docs/project_artefacts/SWOT/analise_swot.jpg
  docs/project_artefacts/SWOT/index.md
  docs/project_artefacts/eap/eap_produto.jpg
  docs/project_artefacts/eap/index.md
Labels: documentation, easy, gh-pages
