Repository fga-gpp-mds/2018.1-TropicalHazards-BI, pull requests merged in 2018-03, with the labels that each got.

#1 [ADD] .github folder with templates for issues/pr
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/bug_report.md
  .github/epic.md
  .github/feature.md
  .github/how-to-use-templates.md
Labels: pending review

#2 [ADD] codeofconduct file and template
  CODE_OF_CONDUCT.md
Labels: work in progress

#12 license file (MIT)
  CODE_OF_CONDUCT.md
  LICENSE
Labels: pending review

#27 Issue #26 - Criar políticas de repositorios
  .github/politica_de_branches.md
  .github/politica_de_commit.md
Labels: documentation, pending review

#29 Templates for sprint planning and review
  docs/templates/sprint_planning.md
  docs/templates/sprint_review.md
Labels: documentation

#32 [ADD] create sprint 01 planning
  docs/templates/sprint_01/sprint_01_planning.md
Labels: documentation

#42 Issue 25 create gh pages
  docs/.github/CONTRIBUTING.md
  docs/.github/ISSUE_TEMPLATE.md
  docs/.github/PULL_REQUEST_TEMPLATE.md
  docs/.github/bug_report.md
  docs/.github/epic.md
  docs/.github/feature.md
  docs/.github/how-to-use-templates.md
  docs/.github/politica_de_branches.md
  docs/.github/politica_de_commit.md
  docs/_config.yml
  docs/_layouts/default.html
  docs/css/shared.css
  docs/docsmap.html
  docs/index.html
  docs/sprint_0/sprint_0_planning.md
  docs/sprint_0/sprint_0_review.md
  docs/sprint_01/sprint_01_planning.md
Labels: documentation, enhancement, pending review, repo workflow

#37 close #4 EAP creation
  docs/EAP/Tropical Hazards BI.png
Labels: EPS, documentation

#57 [FIX] issue #36 and #51 repo organization related issues
  CONTRIBUTING.md
  docs/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  docs/ISSUE_TEMPLATE/bug_report.md
  docs/ISSUE_TEMPLATE/epic.md
  docs/ISSUE_TEMPLATE/feature.md
  docs/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  docs/how-to-use-templates.md
  docs/policies/politica_de_branches.md
  docs/policies/politica_de_commit.md
  docs/wiki/EAP/Tropical Hazards BI.png
  docs/wiki/R1/sprint_00/sprint_00_planning.md
  docs/wiki/R1/sprint_00/sprint_00_review.md
  docs/wiki/R1/sprint_01/sprint_01_planning.md
Labels: pending review, repo workflow

#58 [FIX] closes #55 Travis CI integration and Code Climate
  .travis.yml
  Dockerfile
  README.md
  TropicalHazards_BI/.env_test
  TropicalHazards_BI/__init__.py
  TropicalHazards_BI/settings.py
  TropicalHazards_BI/urls.py
  TropicalHazards_BI/wsgi.py
  boot.sh
  docker-compose.yml
  manage.py
  pytest.ini
  requirements.txt
Labels: EPS, enhancement, pending review

#59 Issue 13 refact important documentation to maintain the repository organization
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  docs/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  docs/ISSUE_TEMPLATE/bug_report.md
  docs/ISSUE_TEMPLATE/epic.md
  docs/ISSUE_TEMPLATE/feature.md
  docs/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#64 [MERGE] refactoring EAP
  docs/wiki/EAP/Tropical Hazards BI.png
Labels: EPS, documentation, enhancement, pending review

#70 [ADD] #69 commit template
  docs/.gitmessage
Labels: documentation, enhancement, pending review

#71 Issue 10 doc visao
  docs/doc_visao.md
Labels: documentation, pending review

#68 [UPDATE] Including README description
  README.md
Labels: EPS, pending review

#63 [DOC] create documetation about methodologies used
  docs/metodologia.md
Labels: EPS, documentation, help wanted, work in progress

#80 Issue 34 fix sprints docs
  docs/templates/sprint_planning.md
  docs/templates/sprint_review.md
  docs/wiki/R1/sprint_00/sprint_00_planning.md
  docs/wiki/R1/sprint_00/sprint_00_review.md
  docs/wiki/R1/sprint_01/sprint_01_planning.md
  docs/wiki/R1/sprint_01/sprint_01_review.md
  docs/wiki/R1/sprint_02/sprint_02_planning.md
Labels: documentation, pending review

#73 issue 53 - Refactoring topic 2 in architecture document
  docs/doc_arquitetura.md
Labels: MDS, documentation, medium, pending review

#112 issue 43 ghpages fill
  docs/ISSUE_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
  docs/_layouts/default.html
  docs/css/shared.css
  docs/docsmap.html
  docs/index.html
  docs/wiki/EAP/index.md
Labels: Important, Not planned, TS, design, enhancement, gh-pages, hotfix, pending review, repo workflow

#96 Issue 5 - TAP
  docs/wiki/TAP/TAP.md
Labels: EPS, documentation, medium, pending review

#111 issue 62 refatorar EAP
  docs/wiki/EAP/Tropical Hazards BI.png
Labels: EPS, documentation, enhancement, pending review

#108 Issue 106 Chages the database container port
  docker-compose.yml
Labels: dev-ops, docker, pending review

#110 Issue 88 criacao usuario api
  TropicalHazards_BI/settings.py
  TropicalHazards_BI/urls.py
  manage.py
  requirements.txt
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/serializers.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: MDS, Planned, US, enhancement, pending review

#120 Issue 7 Produzir artefato Roadmap
  docs/wiki/ROADMAP/Roadmap.png
  docs/wiki/ROADMAP/Timeline_Cliente.png
  docs/wiki/ROADMAP/Timeline_Features_And_US.png
Labels: EPS, Too important!, documentation, enhancement, pending review

#122 Sprint documentation improvement
  docs/wiki/R1/sprint_01/sprint_01_planning.md
  docs/wiki/R1/sprint_01/sprint_01_review.md
  docs/wiki/R1/sprint_02/sprint_02_planning.md
  docs/wiki/R1/sprint_02/sprint_02_review.md
  docs/wiki/R1/sprint_03/sprint_03_planning.md
Labels: EPS, Scrum Master, documentation, pending review

#123 [DOC] adding measure planning
  docs/wiki/plano-de-medicao.md
Labels: EPS, documentation, enhancement, hard, pending review

#116 Issue 93 fix psycopg
  .travis.yml
  requirements.txt
Labels: EPS, bug, dependencies, enhancement, pending review

#109 Issue 83 metas e restricoes doc architecture
  docs/doc_arquitetura.md
Labels: Architect, EPS, MDS, Too important!, documentation, pending review

#125 [MERGE] Sprint 03
  .travis.yml
  TropicalHazards_BI/settings.py
  TropicalHazards_BI/urls.py
  docker-compose.yml
  docs/doc_arquitetura.md
  docs/wiki/EAP/Tropical Hazards BI.png
  docs/wiki/R1/sprint_01/sprint_01_planning.md
  docs/wiki/R1/sprint_01/sprint_01_review.md
  docs/wiki/R1/sprint_02/sprint_02_planning.md
  docs/wiki/R1/sprint_02/sprint_02_review.md
  docs/wiki/R1/sprint_03/sprint_03_planning.md
  docs/wiki/ROADMAP/Roadmap.png
  docs/wiki/ROADMAP/Timeline_Cliente.png
  docs/wiki/ROADMAP/Timeline_Features_And_US.png
  docs/wiki/TAP/TAP.md
  docs/wiki/plano-de-medicao.md
  manage.py
  requirements.txt
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/serializers.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: EPS, Important, MDS, dependencies, dev-ops, documentation, enhancement, pending review
