Repository fga-gpp-mds/2018.1-TropicalHazards-BI, pull requests merged in 2018-06, with the labels that each got.

#336 Sprint 12 review e Sprint 13 planning
  docs/metodology/sprints/sprint_10/sprint_10_planning.md
  docs/metodology/sprints/sprint_10/sprint_10_review.md
  docs/metodology/sprints/sprint_11/sprint_11_planning.md
  docs/metodology/sprints/sprint_11/sprint_11_review.md
  docs/metodology/sprints/sprint_12/sprint_12_planning.md
  docs/metodology/sprints/sprint_12/sprint_12_review.md
  docs/metodology/sprints/sprint_13/sprint_13_planning.md
Labels: EPS, Scrum Master, documentation

#337 Issue 242 refactoring test
  dashboards/tests.py
  projects/tests.py
  tags/tests.py
  users/tests.py
Labels: MDS, enhancement, pending review, refactoring

#338 Atualizar documentação do burndown de riscos no ghpages
  docs/metodology/sprints/sprint_13/sprint_13_review.md
Labels: EPS, Planned, Scrum Master, documentation, pending review

#346 Issue 331 relate project with metabase table
  TropicalHazards_BI/utils.py
  import_data/tests.py
  import_data/views.py
  metabase/utils.py
  metabase/views.py
  projects/models.py
  projects/serializers.py
  projects/tests.py
  projects/views.py
Labels: Architect, enhancement, pending review

#349 Sprint 13 review and sprint 14 planning
  docs/index.html
  docs/metodology/sprints/sprint_12/sprint_12_planning.md
  docs/metodology/sprints/sprint_13/sprint_13_review.md
  docs/metodology/sprints/sprint_14/sprint_14_planning.md
Labels: EPS, Scrum Master, documentation, enhancement

#345 Issue 335 Definir dimenções de um gráfico
  metabase/admin.py
  metabase/utils.py
  metabase/views.py
Labels: Too important!, pending review

#351 Novo end point para retorno de lista de projetos do usuário logado
  projects/tests.py
  projects/urls.py
  projects/views.py
Labels: pending review

#353 Coleta métrica de deploy contínuo
  .travis.yml
Labels: EPS, dev-ops, enhancement

#356 [DOC] Adding Sprint 14 Review and Sprint 15 planning
  docs/index.html
  docs/metodology/sprints/sprint_13/sprint_13_review.md
  docs/metodology/sprints/sprint_14/sprint_14_review.md
  docs/metodology/sprints/sprint_15/sprint_15_planning.md
Labels: EPS, Scrum Master, documentation, pending review

#360 Documenção do pipeline DevOps
  docs/_layouts/default.html
  docs/index.html
  docs/project_artefacts/pipeline_devops/index.md
  docs/project_artefacts/pipeline_devops/pipeline_DevOps.png
Labels: EPS, dev-ops, documentation, enhancement, gh-pages

#358 Filtro para criação de Iframe
  metabase/views.py
Labels: easy, pending review

#364 Validate metabase auth token
  metabase/utils.py
Labels: Architect, Not planned, pending review

#367 Corrige tratamento ao receber dimensões vazias
  metabase/views.py
Labels: Architect, bug, enhancement, pending review

#370 [UPDATE] changes to logout method
  TropicalHazards_BI/settings.py
Labels: pending review

#373 Sincroniza metabase com mongo depois de upload
  import_data/tests.py
  import_data/views.py
Labels: Architect, bug, enhancement, pending review

#376 [FIX] fixed visualization settings
  metabase/views.py
Labels: Too important!
