Repository fga-gpp-mds/2018.1-TropicalHazards-BI, pull requests merged in 2018-05, with the labels that each got.

#259 Update do tópico de Visão de Dados atualizando diagrama ER
  docs/development_docs/doc_arquitetura.md
Labels: easy, pending review

#263 Adds release-it tool for making releases
  .gitignore
  package.json
Labels: Too important!

#265 Issue 253 Metabase dev configuration
  .env
  .gitignore
  docker-compose.yml
Labels: Architect, EPS, Planned, dev-ops, docker, enhancement, pending review

#266 Sprint documentation
  docs/metodology/sprints/sprint_05/sprint_05_review.md
  docs/metodology/sprints/sprint_06/sprint_06_planning.md
  docs/metodology/sprints/sprint_06/sprint_06_review.md
  docs/metodology/sprints/sprint_07/sprint_07_planning.md
  docs/metodology/sprints/sprint_07/sprint_07_review.md
  docs/metodology/sprints/sprint_08/sprint_08_planning.md
Labels: Scrum Master, documentation, enhancement, pending review

#284 Issue 213 Importar CSV
  .gitignore
  TropicalHazards_BI/settings.py
  TropicalHazards_BI/urls.py
  import_data/__init__.py
  import_data/admin.py
  import_data/apps.py
  import_data/migrations/__init__.py
  import_data/models.py
  import_data/serializers.py
  import_data/tests.py
  import_data/urls.py
  import_data/views.py
  requirements.txt
  tmp/.gitkeep
Labels: Important, pending review

#275 Issue 274 atualizar ghpages
  docs/index.html
Labels: documentation, easy, hotfix

#287 Issue 271 config mongo metabase
  .env
  TropicalHazards_BI/meteabase_setup.py
  docker-compose.yml
  requirements.txt
Labels: Architect, EPS, enhancement, pending review

#286 [FIX] fix urls with incorrect sintax
  projects/tests.py
  projects/urls.py
  users/tests.py
  users/urls.py
Labels: pending review

#294 Issue 268 Filtrar Import Data
  import_data/urls.py
  import_data/views.py
  requirements.txt
Labels: MDS, Planned, enhancement, pending review

#292 Issue 269 Procurar Projetos por Tag
  .gitignore
  TropicalHazards_BI/settings.py
  projects/filters.py
  projects/models.py
  projects/views.py
  requirements.txt
Labels: dependencies, pending review

#301 Issue 77 front usability test
  docs/project_artefacts/usability_test/index.md
  package.json
Labels: EPS, Planned, documentation, enhancement

#297 Adicionar Diagrama de Experiencia de Usuário a pasta imagens
  docs/UX/Fluxograma_nav.png
  docs/UX/index.md
  docs/index.html
Labels: EPS, MDS, documentation, enhancement

#298 Issue 254 Definir tipo de dados
  import_data/views.py
Labels: Important, Too important!, pending review

#306 Issue 291 Metabase Setup
  .dockerignore
  docker-compose.yml
  metabase-docker/Dockerfile
  metabase-docker/metabase_setup.py
  metabase-docker/requirements.txt
  metabase-docker/start.sh
Labels: EPS, Too important!, dev-ops, enhancement, pending review

#299 Issue 290 environment vars
  .gitignore
  .travis.yml
  README.md
  TropicalHazards_BI/settings.py
  env.tmpl
  nginx/Dockerfile
  nginx/nginx.conf
Labels: EPS, dev-ops, enhancement, pending review

#293 Issue 276 validação para editar/deletar tags
  tags/tests.py
  tags/views.py
Labels: pending review

#310 Issue 309 Configure sentry to watch the app
  TropicalHazards_BI/settings.py
  requirements.txt
Labels: dev-ops, enhancement, pending review

#311 [HOTFIX] fix migrations folders and gitignore config
  .gitignore
  boot.sh
  dashboards/migrations/__init__.py
  import_data/migrations/__init__.py
  projects/migrations/__init__.py
  tags/migrations/__init__.py
  users/migrations/__init__.py
Labels: Too important!, bug, dev-ops, enhancement

#316 Sprint docs
  docs/metodology/sprints/sprint_07/sprint_07_review.md
  docs/metodology/sprints/sprint_08/sprint_08_review.md
  docs/metodology/sprints/sprint_09/sprint_09_planning.md
  docs/metodology/sprints/sprint_09/sprint_09_review.md
  docs/metodology/sprints/sprint_10/sprint_10_planning.md
  docs/metodology/sprints/sprint_10/sprint_10_review.md
  docs/metodology/sprints/sprint_11/sprint_11_planning.md
Labels: EPS, Scrum Master, documentation, pending review

#315 Configures semantic release
  .travis.yml
  package.json
Labels: pending review

#318 [HOTFIX] fix travis deploy to rancher
  .dockerignore
  .gitignore
  .travis.yml
  semantic-release.sh
  travis-deploy.sh
Labels: EPS, bug, dev-ops, hotfix

#320 Issue 303 make question in metabase
  TropicalHazards_BI/settings.py
  TropicalHazards_BI/urls.py
  metabase-docker/metabase_setup.py
  metabase/__init__.py
  metabase/admin.py
  metabase/apps.py
  metabase/migrations/__init__.py
  metabase/models.py
  metabase/serializers.py
  metabase/tests.py
  metabase/urls.py
  metabase/utils.py
  metabase/views.py
  requirements.txt
Labels: EPS, MDS, enhancement, hard, pending review

#327 [HOTFIX] fixes the automated release error
  package.json
Labels: hotfix

#330 Relatório da etapa 1 dos testes de usabilidade
  docs/UX/front_roadmap.png
  docs/UX/index.md
  docs/UX/usability_test/relatorio_teste1.md
  docs/index.html
Labels: EPS, documentation, enhancement
